# Generated by Django 4.1.3 on 2024-12-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_category_user_postcategory_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttag',
            name='tagid',
        ),
        migrations.AddField(
            model_name='posttag',
            name='post_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tagposts', to='rareapi.post'),
        ),
        migrations.AddField(
            model_name='posttag',
            name='tag_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posttags', to='rareapi.tag'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rareapi.category'),
            preserve_default=False,
        ),
    ]
