# Generated by Django 4.2.15 on 2024-12-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_category'),
        ('rareapi', '0002_category_user_postcategory_post_comments'),
    ]

    operations = [
    ]
